// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIIJntg_2-R4vgc_JaS0Q-UhEhD3jC4LI',
    appId: '1:901306230100:web:987abe8c041e8007b194c1',
    messagingSenderId: '901306230100',
    projectId: 'yumly-b1bb6',
    authDomain: 'yumly-b1bb6.firebaseapp.com',
    storageBucket: 'yumly-b1bb6.firebasestorage.app',
    measurementId: 'G-95X4GZP50L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtkBiz9joc7VQbJKnmuZovY3_ToCRTjg',
    appId: '1:901306230100:android:17780bc3c0a2d915b194c1',
    messagingSenderId: '901306230100',
    projectId: 'yumly-b1bb6',
    storageBucket: 'yumly-b1bb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiXPaGKczZ-nsvyS9xm4k5C1nWG5sUaKI',
    appId: '1:901306230100:ios:5911c1042bbdc797b194c1',
    messagingSenderId: '901306230100',
    projectId: 'yumly-b1bb6',
    storageBucket: 'yumly-b1bb6.firebasestorage.app',
    iosBundleId: 'com.example.yumly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiXPaGKczZ-nsvyS9xm4k5C1nWG5sUaKI',
    appId: '1:901306230100:ios:5911c1042bbdc797b194c1',
    messagingSenderId: '901306230100',
    projectId: 'yumly-b1bb6',
    storageBucket: 'yumly-b1bb6.firebasestorage.app',
    iosBundleId: 'com.example.yumly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIIJntg_2-R4vgc_JaS0Q-UhEhD3jC4LI',
    appId: '1:901306230100:web:b8d437930f7abac5b194c1',
    messagingSenderId: '901306230100',
    projectId: 'yumly-b1bb6',
    authDomain: 'yumly-b1bb6.firebaseapp.com',
    storageBucket: 'yumly-b1bb6.firebasestorage.app',
    measurementId: 'G-6XZCKXWRNX',
  );
}
